### PR TITLE
[modication] added controller editProduct.

### PR DESCRIPTION
**Pull request by 1Orchestratooor1**
Changed name of  Logic Delete before updateProduct to eliminationProduct and eliminated removedProduct and deleteProduct controllers that are not used.

### CODE REVIEW

**Comment by garaven** [comment]
Did you test the code?

**Comment by Gothsec** [comment]
yo, I have a question, we don't have the Orders option in the navbar, I should do that? I'm actually working on create orders

**Comment by garaven** [comment]
> yo, I have a question, we don't have the Orders option in the navbar, should I do that? I'm actually working on create orders

Yes, I forgot that

**Comment by 1Orchestratooor1** [comment]
You are right, the "eliminationProduct" controller is missing, but it works since the fetch was referring to the previous "updateProduct" that I did not delete, and I also did not change the endpoint; it was my oversight. Please reject the push; I am still working on it and haven’t finished yet.

**Review by garaven — CHANGES_REQUESTED** [review]
Add the endpoint for 'elimination product' function

**Comment by 1Orchestratooor1** [comment]
mmm, I have already modified the "endpoint" file and "ProductRow" to implement the "infoProduct" function, and I haven’t finished yet. I can’t do the push because it would include the changes for the mentioned implementation.

**Pull request closed without merging**
